# Generated by Django 3.1 on 2020-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('1', 'Yet to Contact'), ('2', 'In progress'), ('3', 'No response from customer'), ('4', 'Success'), ('5', 'Failure'), ('6', 'Not interested right now but will be in future')], max_length=20)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
