# Generated by Django 3.1 on 2020-08-22 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userquery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='status',
            field=models.CharField(choices=[('1', 'Yet to Contact'), ('2', 'In progress'), ('3', 'No response from customer'), ('4', 'Success'), ('5', 'Failure'), ('6', 'Not interested right now but will be in future')], default='1', max_length=20),
        ),
    ]
